project:
  type: website
  output-dir: docs

website:
  title: "Parker Otto - MUSA 5080 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Labs
        menu:
          - href: lab/lab_0/lab0_template.qmd
            text: "Lab 0: dplyr Basics"
          - href: labs/lab_1/lab_1.qmd
            text: "Lab 1: Census Data Exploration"
      - text: Weekly Notes
        menu: 
          - href: weekly-notes/
            text: "Coming Soon!"
      - text: Final Project
        menu:
          - href: final/
            text: "Coming Soon!"

format:
  html:
    theme: darkly
    toc: true
    code-fold: true

execute:
  freeze: auto
